spring.application.name=employee-management

spring.datasource.url=jdbc:postgresql://ep-icy-lake-azpjptjj.c-3.ap-southeast-1.aws.neon.tech:5432/neondb?sslmode=require
spring.datasource.username=neondb_owner
spring.datasource.password=npg_AZFb20KuLmsD

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
